services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: photon

  prometheus:
    image: prom/prometheus:v2.52.0
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  api:
    networks:
      default:
        aliases:
          - photon-api
    build:
      context: ../services/api
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/photon?sslmode=disable
      PORT: "8080"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: unless-stopped

  ui:
    build:
      context: ../services/ui
    ports:
      - "8081:80"
    depends_on:
      - api

volumes: {}
